hostname = rec.xiaohongshu.com, edith.xiaohongshu.com, www.xiaohongshu.com

^https?:\/\/[a-z]+\.xiaohongshu\.com\/api\/sns\/v\d+\/homefeed\? url response-body "display_title":"([^"]+)" response-body "display_title":"✅DIAG-$1"
