hostname = rec.xiaohongshu.com, edith.xiaohongshu.com, www.xiaohongshu.com

^https?:\/\/[a-z]+\.xiaohongshu\.com\/api\/sns\/v\d+\/homefeed\? url script-response-body https://raw.githubusercontent.com/meichiny/rednote-feed-time/shadowrocket-module/modules/quantumultx/rednote-feed-time-test.js
