#!name=小红书Feed时间-诊断
#!desc=诊断：将第一条笔记标题替换为 ✅DIAG-xxxxxx

[rewrite_local]
^https?:\/\/[a-z]+\.xiaohongshu\.com\/api\/sns\/v\d+\/homefeed\? url script-response-body https://raw.githubusercontent.com/meichiny/rednote-feed-time/shadowrocket-module/modules/quantumultx/rednote-feed-time-test.js

[MITM]
hostname = rec.xiaohongshu.com, edith.xiaohongshu.com
